---
deployment:
  tasks:
    - source /home/datangle/virtualenv/mypythonapp/3.7/bin/activate && cd /home/datangle/mypythonapp
    - export DEPLOYPATH=/home/datangle/mypythonapp/
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp app.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
